version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: keycloak-demo-db
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE:-keycloak}
      POSTGRES_USER: ${DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-keycloak}
  keycloak:
    container_name: demo-keycloak
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${DB_DATABASE:-keycloak}
      DB_USER: ${DB_USER:-keycloak}
      DB_PASSWORD: ${DB_PASSWORD:-keycloak}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_LOGLEVEL: ${KEYCLOAK_LOGLEVEL:-INFO}
      PROXY_ADDRESS_FORWARDING: ${PROXY_ADDRESS_FORWARDING:-true}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}      
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below
      # is just an example, and it shouldn't be used in production without knowledge.
      # It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    command: [ "${KEYCLOAK_START_CMD}" ]
#    ports:
#    - ${KEYCLOAK_PORT:-8080}:8080
    depends_on:
    - postgres
